services:
  eldoria:
    image: ghcr.io/gass-an/eldoria-bot:${APP_VERSION}
    container_name: eldoria-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Persiste la DB SQLite et tout ce qui est écrit dans /app/data
      - ./data:/app/data

      # Logs du bot
      - ./logs:/app/logs
    security_opt:
      - no-new-privileges:true